name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Build
        run: cargo build --verbose
        with:
          toolchain: nightly
          override: true
#      - name: Run tests
#        run: cargo test --verbose